# Generated by Django 3.2.21 on 2023-09-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='nabek', max_length=255),
            preserve_default=False,
        ),
    ]
