# Generated by Django 3.2.21 on 2023-09-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
    ]
